-- This is optional seed data for testing
-- You can run this after user signup to test the platform

-- Note: User IDs will be generated by Supabase Auth
-- This is just example structure for when you want to add test data
